package com.cappuccino.offer.domain.ad;

import java.math.BigDecimal;

public class Ads {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_ads.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_ads.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_ads.provider_id
     *
     * @mbggenerated
     */
    private Integer providerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_ads.pkg
     *
     * @mbggenerated
     */
    private String pkg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_ads.offrerid
     *
     * @mbggenerated
     */
    private String offrerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_ads.payout
     *
     * @mbggenerated
     */
    private BigDecimal payout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_ads.payout_type
     *
     * @mbggenerated
     */
    private Byte payoutType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_ads.tracklink
     *
     * @mbggenerated
     */
    private String tracklink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_ads.previewlink
     *
     * @mbggenerated
     */
    private String previewlink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_ads.countries
     *
     * @mbggenerated
     */
    private String countries;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_ads.platform
     *
     * @mbggenerated
     */
    private Byte platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_ads.icon
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_ads.creative_files
     *
     * @mbggenerated
     */
    private String creativeFiles;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_ads.incentive
     *
     * @mbggenerated
     */
    private Byte incentive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_ads.os_min_version
     *
     * @mbggenerated
     */
    private Byte osMinVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_ads.carriers
     *
     * @mbggenerated
     */
    private String carriers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_ads.cap
     *
     * @mbggenerated
     */
    private Byte cap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_ads.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_ads.id
     *
     * @return the value of o_ads.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_ads.id
     *
     * @param id the value for o_ads.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_ads.name
     *
     * @return the value of o_ads.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_ads.name
     *
     * @param name the value for o_ads.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_ads.provider_id
     *
     * @return the value of o_ads.provider_id
     *
     * @mbggenerated
     */
    public Integer getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_ads.provider_id
     *
     * @param providerId the value for o_ads.provider_id
     *
     * @mbggenerated
     */
    public void setProviderId(Integer providerId) {
        this.providerId = providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_ads.pkg
     *
     * @return the value of o_ads.pkg
     *
     * @mbggenerated
     */
    public String getPkg() {
        return pkg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_ads.pkg
     *
     * @param pkg the value for o_ads.pkg
     *
     * @mbggenerated
     */
    public void setPkg(String pkg) {
        this.pkg = pkg == null ? null : pkg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_ads.offrerid
     *
     * @return the value of o_ads.offrerid
     *
     * @mbggenerated
     */
    public String getOffrerid() {
        return offrerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_ads.offrerid
     *
     * @param offrerid the value for o_ads.offrerid
     *
     * @mbggenerated
     */
    public void setOffrerid(String offrerid) {
        this.offrerid = offrerid == null ? null : offrerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_ads.payout
     *
     * @return the value of o_ads.payout
     *
     * @mbggenerated
     */
    public BigDecimal getPayout() {
        return payout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_ads.payout
     *
     * @param payout the value for o_ads.payout
     *
     * @mbggenerated
     */
    public void setPayout(BigDecimal payout) {
        this.payout = payout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_ads.payout_type
     *
     * @return the value of o_ads.payout_type
     *
     * @mbggenerated
     */
    public Byte getPayoutType() {
        return payoutType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_ads.payout_type
     *
     * @param payoutType the value for o_ads.payout_type
     *
     * @mbggenerated
     */
    public void setPayoutType(Byte payoutType) {
        this.payoutType = payoutType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_ads.tracklink
     *
     * @return the value of o_ads.tracklink
     *
     * @mbggenerated
     */
    public String getTracklink() {
        return tracklink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_ads.tracklink
     *
     * @param tracklink the value for o_ads.tracklink
     *
     * @mbggenerated
     */
    public void setTracklink(String tracklink) {
        this.tracklink = tracklink == null ? null : tracklink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_ads.previewlink
     *
     * @return the value of o_ads.previewlink
     *
     * @mbggenerated
     */
    public String getPreviewlink() {
        return previewlink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_ads.previewlink
     *
     * @param previewlink the value for o_ads.previewlink
     *
     * @mbggenerated
     */
    public void setPreviewlink(String previewlink) {
        this.previewlink = previewlink == null ? null : previewlink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_ads.countries
     *
     * @return the value of o_ads.countries
     *
     * @mbggenerated
     */
    public String getCountries() {
        return countries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_ads.countries
     *
     * @param countries the value for o_ads.countries
     *
     * @mbggenerated
     */
    public void setCountries(String countries) {
        this.countries = countries == null ? null : countries.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_ads.platform
     *
     * @return the value of o_ads.platform
     *
     * @mbggenerated
     */
    public Byte getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_ads.platform
     *
     * @param platform the value for o_ads.platform
     *
     * @mbggenerated
     */
    public void setPlatform(Byte platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_ads.icon
     *
     * @return the value of o_ads.icon
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_ads.icon
     *
     * @param icon the value for o_ads.icon
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_ads.creative_files
     *
     * @return the value of o_ads.creative_files
     *
     * @mbggenerated
     */
    public String getCreativeFiles() {
        return creativeFiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_ads.creative_files
     *
     * @param creativeFiles the value for o_ads.creative_files
     *
     * @mbggenerated
     */
    public void setCreativeFiles(String creativeFiles) {
        this.creativeFiles = creativeFiles == null ? null : creativeFiles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_ads.incentive
     *
     * @return the value of o_ads.incentive
     *
     * @mbggenerated
     */
    public Byte getIncentive() {
        return incentive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_ads.incentive
     *
     * @param incentive the value for o_ads.incentive
     *
     * @mbggenerated
     */
    public void setIncentive(Byte incentive) {
        this.incentive = incentive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_ads.os_min_version
     *
     * @return the value of o_ads.os_min_version
     *
     * @mbggenerated
     */
    public Byte getOsMinVersion() {
        return osMinVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_ads.os_min_version
     *
     * @param osMinVersion the value for o_ads.os_min_version
     *
     * @mbggenerated
     */
    public void setOsMinVersion(Byte osMinVersion) {
        this.osMinVersion = osMinVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_ads.carriers
     *
     * @return the value of o_ads.carriers
     *
     * @mbggenerated
     */
    public String getCarriers() {
        return carriers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_ads.carriers
     *
     * @param carriers the value for o_ads.carriers
     *
     * @mbggenerated
     */
    public void setCarriers(String carriers) {
        this.carriers = carriers == null ? null : carriers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_ads.cap
     *
     * @return the value of o_ads.cap
     *
     * @mbggenerated
     */
    public Byte getCap() {
        return cap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_ads.cap
     *
     * @param cap the value for o_ads.cap
     *
     * @mbggenerated
     */
    public void setCap(Byte cap) {
        this.cap = cap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_ads.status
     *
     * @return the value of o_ads.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_ads.status
     *
     * @param status the value for o_ads.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}